# Form implementation generated from reading ui file 'windows/about.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_about(object):
    def setupUi(self, about):
        about.setObjectName("about")
        about.resize(295, 301)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(about.sizePolicy().hasHeightForWidth())
        about.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(about)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(about)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.desc = QtWidgets.QLabel(about)
        self.desc.setObjectName("desc")
        self.verticalLayout.addWidget(self.desc)
        self.legal = QtWidgets.QPlainTextEdit(about)
        self.legal.setReadOnly(True)
        self.legal.setObjectName("legal")
        self.verticalLayout.addWidget(self.legal)
        self.licenseButton = QtWidgets.QPushButton(about)
        self.licenseButton.setObjectName("licenseButton")
        self.verticalLayout.addWidget(self.licenseButton)

        self.retranslateUi(about)
        QtCore.QMetaObject.connectSlotsByName(about)

    def retranslateUi(self, about):
        _translate = QtCore.QCoreApplication.translate
        about.setWindowTitle(_translate("about", "About"))
        self.title.setText(_translate("about", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">neeshibutton</span></p></body></html>"))
        self.desc.setText(_translate("about", "<html><head/><body><p align=\"center\">Generate a nee shi-style message</p></body></html>"))
        self.legal.setPlainText(_translate("about", "neeshibutton  Copyright (C) 2022 Eric Zhang\n"
"\n"
"This program comes with ABSOLUTELY NO WARRANTY; for details click \"License\".\n"
"\n"
"This is free software, and you are welcome to redistribute it under certain conditions; click \"License\" for details."))
        self.licenseButton.setText(_translate("about", "License"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    about = QtWidgets.QDialog()
    ui = Ui_about()
    ui.setupUi(about)
    about.show()
    sys.exit(app.exec())
