# Form implementation generated from reading ui file 'windows/mainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(310, 327)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.neeshiLabel = QtWidgets.QLabel(self.centralwidget)
        self.neeshiLabel.setObjectName("neeshiLabel")
        self.gridLayout.addWidget(self.neeshiLabel, 0, 0, 1, 2)
        self.neeshiButton = QtWidgets.QPushButton(self.centralwidget)
        self.neeshiButton.setObjectName("neeshiButton")
        self.gridLayout.addWidget(self.neeshiButton, 1, 0, 1, 1)
        self.neeshiClear = QtWidgets.QPushButton(self.centralwidget)
        self.neeshiClear.setObjectName("neeshiClear")
        self.gridLayout.addWidget(self.neeshiClear, 1, 1, 1, 1)
        self.neeshiMsg = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.neeshiMsg.setUndoRedoEnabled(False)
        self.neeshiMsg.setReadOnly(True)
        self.neeshiMsg.setPlainText("")
        self.neeshiMsg.setPlaceholderText("")
        self.neeshiMsg.setObjectName("neeshiMsg")
        self.gridLayout.addWidget(self.neeshiMsg, 2, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 2)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 310, 29))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(mainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionQuit = QtGui.QAction(mainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainWindow)
        self.neeshiClear.clicked.connect(self.neeshiMsg.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.neeshiButton, self.neeshiClear)
        mainWindow.setTabOrder(self.neeshiClear, self.neeshiMsg)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Nee shi message generator"))
        self.neeshiLabel.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Nee shi message generator</span></p></body></html>"))
        self.neeshiButton.setText(_translate("mainWindow", "Generate"))
        self.neeshiClear.setText(_translate("mainWindow", "Clear"))
        self.label.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">Clicking &quot;Generate&quot; means you agree to the GNU General Public License version 3 (or later). Click &quot;About&quot; in the &quot;Help&quot; menu for more details.</span></p></body></html>"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.menuHelp.setTitle(_translate("mainWindow", "Help"))
        self.actionAbout.setText(_translate("mainWindow", "About"))
        self.actionQuit.setText(_translate("mainWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec())
